### ISSUE TITLE
rutas que contienen paréntesis

### ISSUE THREAD

**Issue by alete89** [alete89/nPy#12]
El sistema utilizado para definir los parámetros no prevé que las rutas pueden tener paréntesis. Por ejemplo, en sistemas windows de 64 bits, muchos programas son instalados en `c:\program files (x86)\`
Esto ocasiona que al querer lanzar un programa desde esa ruta, nPy solicite un parámetro con el placeholder "x86" y finalmente el programa no se pueda lanzar.

Quizás habría que cambiar los delimitadores por: <>, o ¿?

Con algún cambio, también podrían ser iguales, por ejemplo: ^parametro^

@manublesa

**Comment by manublesa** [comment]
Hola Ale,
Estoy de acuerdo, cambia los delimitados por los caracteres que creas
conveniente... los símbolos mayor-mejor me parecen bien.
Abrazo.

**Comment by alete89** [comment]
fixed with commit 08ef812b31bd63981d94c18e85664b9797b40d64
